# Bu dosya GitHub Sponsors için kullanılır
# Eğer projeyi desteklemek isterseniz, buraya link ekleyebilirsiniz

# github: [kullanıcı_adı] # GitHub Sponsors
# patreon: # Patreon kullanıcı adı
# open_collective: # Open Collective kullanıcı adı
# ko_fi: # Ko-fi kullanıcı adı
# custom: # Özel bağış linki
